print()
print()
print()
print("   Enter number = 65")
print("   Sum of digits of the number is : 11")
print()
print()
print()
print("   Enter number = 657")
print("   Reverse of the given number is 756")
print()
print()
print("   Enter number = 7")
print("   The number is Prime")
print()
print()
print()
print("   Enter First number : 90")
print("   Enter Second number : 70")
print("   GCD of 90 and 70 is 10")
print()
print()