# Generated by Django 4.1.4 on 2024-01-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0005_meep_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
